version: "3.8"

services:
    app:
        tty: true
        stdin_open: true
        env_file: ./.env
        restart: on-failure
        volumes:
            - ./:/demo
            - .m2:/root/.m2
        ports:
            - $LOCAL_PORT:$DOCKER_PORT
        build:
            context: ./
            dockerfile: ./src/Dockerfile
